export {
  CancelParcelDocument as CANCEL_PARCEL,
  GetParcelImportDocument as GET_PARCEL_IMPORT,
  GetParcelImportsDocument as GET_PARCEL_IMPORTS,
  GetParcelDocument as PARCEL,
  GetParcelTrackingEventsDocument as GET_PARCEL_TRACKING_EVENTS,
  GetPreLoadParcelsDocument as PRELOAD_PARCELS,
  GetPreLoadParcelsConnectionDocument as PRELOAD_PARCELS_CONNECTION,
  GetParcelsForRouteCreationDocument as PARCELS_FOR_ROUTE,
  RegisterParcelDocument as REGISTER_PARCEL,
  GetRegisteredParcelsDocument as REGISTERED_PARCELS,
  TransitionParcelStatusDocument as TRANSITION_PARCEL_STATUS,
  UpdateParcelDocument as UPDATE_PARCEL,
} from "./generated";
export type {
  CancelParcelMutation,
  CancelParcelMutationVariables,
  GetParcelImportQuery,
  GetParcelImportQueryVariables,
  GetParcelImportsQuery,
  GetParcelImportsQueryVariables,
  GetParcelQuery,
  GetParcelQueryVariables,
  GetParcelTrackingEventsQuery,
  GetParcelTrackingEventsQueryVariables,
  GetPreLoadParcelsQuery,
  GetPreLoadParcelsConnectionQuery,
  GetPreLoadParcelsConnectionQueryVariables,
  GetPreLoadParcelsQueryVariables,
  GetParcelsForRouteCreationQuery,
  GetParcelsForRouteCreationQueryVariables,
  GetRegisteredParcelsQuery,
  GetRegisteredParcelsQueryVariables,
  ParcelFilterInput,
  ParcelSortInput,
  RegisterParcelMutation,
  RegisterParcelMutationVariables,
  TransitionParcelStatusMutation,
  TransitionParcelStatusMutationVariables,
  UpdateParcelMutation,
  UpdateParcelMutationVariables,
} from "./generated";
