export {
  CancelRouteDocument as CANCEL_ROUTE,
  CompleteRouteDocument as COMPLETE_ROUTE,
  CreateRouteDocument as CREATE_ROUTE,
  DispatchRouteDocument as DISPATCH_ROUTE,
  GetMyRouteDocument as GET_MY_ROUTE,
  GetMyRoutesDocument as GET_MY_ROUTES,
  GetRouteAssignmentCandidatesDocument as GET_ROUTE_ASSIGNMENT_CANDIDATES,
  GetRouteDocument as GET_ROUTE,
  GetRoutePlanPreviewDocument as GET_ROUTE_PLAN_PREVIEW,
  GetRoutesDocument as PAGINATED_ROUTES,
  StartRouteDocument as START_ROUTE,
  UpdateRouteAssignmentDocument as UPDATE_ROUTE_ASSIGNMENT,
} from "./generated";

export type {
  CancelRouteMutation,
  CancelRouteMutationVariables,
  CompleteRouteMutation,
  CompleteRouteMutationVariables,
  CreateRouteMutation,
  CreateRouteMutationVariables,
  DispatchRouteMutation,
  DispatchRouteMutationVariables,
  GetMyRouteQuery,
  GetMyRouteQueryVariables,
  GetMyRoutesQuery,
  GetMyRoutesQueryVariables,
  GetRouteAssignmentCandidatesQuery,
  GetRouteAssignmentCandidatesQueryVariables,
  GetRoutePlanPreviewQuery,
  GetRoutePlanPreviewQueryVariables,
  GetRouteQuery,
  GetRouteQueryVariables,
  GetRoutesQuery,
  GetRoutesQueryVariables,
  StartRouteMutation,
  StartRouteMutationVariables,
  StagingArea,
  UpdateRouteAssignmentMutation,
  UpdateRouteAssignmentMutationVariables,
} from "./generated";
