export {
  AddParcelToDispatchedRouteDocument as ADD_PARCEL_TO_DISPATCHED_ROUTE,
  CancelRouteDocument as CANCEL_ROUTE,
  CompleteRouteDocument as COMPLETE_ROUTE,
  CreateRouteDocument as CREATE_ROUTE,
  DispatchRouteDocument as DISPATCH_ROUTE,
  GetDispatchedRouteParcelCandidatesDocument as GET_DISPATCHED_ROUTE_PARCEL_CANDIDATES,
  GetMyRouteDocument as GET_MY_ROUTE,
  GetMyRoutesDocument as GET_MY_ROUTES,
  GetRouteAssignmentCandidatesDocument as GET_ROUTE_ASSIGNMENT_CANDIDATES,
  GetRouteDocument as GET_ROUTE,
  GetRoutesMapDocument as GET_ROUTES_MAP,
  GetRoutePlanPreviewDocument as GET_ROUTE_PLAN_PREVIEW,
  GetRoutesDocument as PAGINATED_ROUTES,
  RemoveParcelFromDispatchedRouteDocument as REMOVE_PARCEL_FROM_DISPATCHED_ROUTE,
  StartRouteDocument as START_ROUTE,
  UpdateRouteAssignmentDocument as UPDATE_ROUTE_ASSIGNMENT,
} from "./generated";

export type {
  AddParcelToDispatchedRouteMutation,
  AddParcelToDispatchedRouteMutationVariables,
  CancelRouteMutation,
  CancelRouteMutationVariables,
  CompleteRouteMutation,
  CompleteRouteMutationVariables,
  CreateRouteMutation,
  CreateRouteMutationVariables,
  DispatchRouteMutation,
  DispatchRouteMutationVariables,
  GetDispatchedRouteParcelCandidatesQuery,
  GetDispatchedRouteParcelCandidatesQueryVariables,
  GetMyRouteQuery,
  GetMyRouteQueryVariables,
  GetMyRoutesQuery,
  GetMyRoutesQueryVariables,
  GetRouteAssignmentCandidatesQuery,
  GetRouteAssignmentCandidatesQueryVariables,
  GetRoutePlanPreviewQuery,
  GetRoutePlanPreviewQueryVariables,
  GetRouteQuery,
  GetRouteQueryVariables,
  GetRoutesMapQuery,
  GetRoutesMapQueryVariables,
  GetRoutesQuery,
  GetRoutesQueryVariables,
  RemoveParcelFromDispatchedRouteMutation,
  RemoveParcelFromDispatchedRouteMutationVariables,
  RouteParcelAdjustmentAction,
  StartRouteMutation,
  StartRouteMutationVariables,
  StagingArea,
  UpdateRouteAssignmentMutation,
  UpdateRouteAssignmentMutationVariables,
} from "./generated";
